# In news_agent_crew/email_service.py

import smtplib
from email.message import EmailMessage
import os
import ssl 
import urllib.parse # <-- NEW IMPORT

# ... (rest of the imports and environment variable setup) ...

def send_post_email(recipient_email: str, post_content: str, topic: str):
    """Sends the generated LinkedIn post with a 'Post Now' CTA button."""
    
    SMTP_SERVER = os.getenv("SMTP_SERVER")
    SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
    SENDER_EMAIL = os.getenv("SENDER_EMAIL")
    SENDER_PASSWORD = os.getenv("SENDER_PASSWORD")

    if not all([SMTP_SERVER, SENDER_EMAIL, SENDER_PASSWORD]):
        print("🔴 ERROR: Email credentials missing. Check your .env file.")
        return

    # 1. URL Encode the post content
    # The post_content is the text the user will share on LinkedIn
    encoded_post = urllib.parse.quote(str(post_content)) 
    linkedin_url = f"https://www.linkedin.com/feed/?shareActive=true&text={encoded_post}"


    # 2. Create the HTML email body with the CTA button
    # Using simple inline CSS for button styling
    html_content = f"""
    <html>
    <body style="font-family: sans-serif; line-height: 1.6; color: #333;">
        <h2 style="color: #0077b5;">✅ Your Curated LinkedIn Post is Ready!</h2>
        <p>Hello,</p>
        <p>Your news agent has successfully generated a LinkedIn post based on your interest in <b>{topic}</b>.</p>
        <p>Review the draft below and use the "Post Now" button to share it directly to LinkedIn.</p>
        
        <div style="border: 1px solid #ccc; padding: 15px; margin: 20px 0; background-color: #f9f9f9; white-space: pre-wrap;">
            <strong>--- DRAFT FOR REVIEW ---</strong><br><br>
            {post_content}
            <br><br><strong>--- END OF DRAFT ---</strong>
        </div>

        <p style="text-align: center; margin: 30px 0;">
            <a href="{linkedin_url}" target="_blank" style="
                background-color: #0077b5; 
                color: white; 
                padding: 12px 25px; 
                text-align: center; 
                text-decoration: none; 
                display: inline-block; 
                border-radius: 4px; 
                font-weight: bold;
                font-size: 16px;
            ">
                🚀 Post Now on LinkedIn
            </a>
        </p>
        
        <p style="font-size: 0.9em; color: #777;">This post was generated by your automated news agent crew.</p>
    </body>
    </html>
    """
    
    # 3. Create the EmailMessage object
    msg = EmailMessage()
    msg['Subject'] = f"✅ Your Curated LinkedIn Post is Ready: {topic}"
    msg['From'] = SENDER_EMAIL
    msg['To'] = recipient_email
    
    # Set the content type to HTML
    msg.set_content("This is an HTML email. Please view it in an HTML-compatible email client.")
    msg.add_alternative(html_content, subtype='html')

    # 4. Secure and send the email
    context = ssl.create_default_context()
    
    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls(context=context)
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.send_message(msg)
            print(f"📧 Email successfully sent to {recipient_email} with CTA.")
            return "Email sent successfully."
            
    except Exception as e:
        print(f"❌ Failed to send email to {recipient_email}. Error: {e}")
        return f"Email failed to send. Error: {e}"